version: '3'
services:
  ai-cheatsheet:
    image: node:latest
    ports:
      - "38029:3000"
    expose:
      - "38029"
    volumes:
      - ./src:/app
    command: sh -c "npm install -g docsify-cli@latest && docsify serve /app/docs"
